/* Needs work */

/* Grammar for CAiml Programming Language */

/* 31 March 2023 (31/03/2023) */

/* BNF Format : test it into https://bnfplayground.pauliankline.com/  */


/* BNF Rules : Lexer and Parser Rules */

/* Lexer Rules */

/* We begin from new elements added to C++23 */

<funcDefinition> ::= decl-
