/* Needs work */

/* BNF Format : test it into https://bnfplayground.pauliankline.com/  */


/* BNF Rules : Lexer and Parser Rules */

/* Lexer Rules */

/* We begin from new elements added to C++23 */

<funcDefinition> ::= decl-
